name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-deply-tasks:
    name: Run deploy tasks
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Check out Git repository
        uses: actions/checkout@v1

      # ESLint and Prettier must be in `package.json`
      - name: Step 2 - Install modules
        run: yarn

      - name: Step 3 - Run eslint
        run: yarn run eslint .

      - name: Step 4 - Build
        run: yarn run build

      - name: Step 5 - Deploy to gh-pages
        run: |
          git config --global user.email "kamionorato@gmail.com"
          git config --global user.name "LadyKamille"
          yarn run deploy
